name: Deploy to Firebase

on:
    push:
        branches:
            - main

jobs:
    build:
        name: Build and Deploy
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.12'

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Add .env variables
              run: |
                  echo "BUCKET_NAME=${{ secrets.BUCKET_NAME }}" >> .env
                  echo "BASE_DIR=${{ secrets.BASE_DIR }}" >> .env
                  echo "GOOGLE_APPLICATION_CREDENTIALS=./firebase-key.json" >> .env
                  echo "DOMAIN_NAME=${{ secrets.DOMAIN_NAME }}" >> .env
                  echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
                  echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env

            - name: Add Firebase service account key
              run: |
                  echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > ./firebase-key.json

            - name: Run Python script
              run: python /Users/_akira/hacker/auto/rw/main.py

            - name: Deploy to Firebase
              uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: '${{ secrets.GITHUB_TOKEN }}'
                  firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
                  channelId: live
                  projectId: cryptoskopen-eu
