name: Deploy to Firebase

on:
    push:
        branches:
            - master

jobs:
    build:
        name: Build and Deploy
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set environment variables
              run: |
                  echo "BUCKET_NAME=${{ secrets.BUCKET_NAME }}" >> $GITHUB_ENV
                  echo "BASE_DIR=${{ github.workspace }}/cryptoskopen-website" >> $GITHUB_ENV
                  echo "GOOGLE_APPLICATION_CREDENTIALS=${{ github.workspace }}/firebase-key.json" >> $GITHUB_ENV
                  echo "DOMAIN_NAME=${{ secrets.DOMAIN_NAME }}" >> $GITHUB_ENV
                  echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
                  echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> $GITHUB_ENV

            - name: Install dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install python3-pip -y
                  pip3 install -r requirements.txt

            - name: Run Python script
              run: python3 rw/main.py
              env:
                  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
                  BASE_DIR: ${{ github.workspace }}/cryptoskopen-website
                  GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/firebase-key.json
                  DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
                  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
                  MONGO_URI: ${{ secrets.MONGO_URI }}

            - name: Deploy to Firebase
              uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: ${{ secrets.GITHUB_TOKEN }}
                  firebaseServiceAccount: ${{ github.workspace }}/firebase-key.json
                  channelId: live
                  projectId: auto-cryptoskopen-1
                  expires: 7d
                  entryPoint: cryptoskopen-website
