name: Deploy to Firebase

on:
    push:
        branches:
            - master

jobs:
    build-and-deploy:
        name: Build and Deploy
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set environment variables
              run: |
                  echo "BUCKET_NAME=${{ secrets.BUCKET_NAME }}" >> $GITHUB_ENV
                  echo "BASE_DIR=${{ secrets.BASE_DIR }}" >> $GITHUB_ENV
                  echo "DOMAIN_NAME=${{ secrets.DOMAIN_NAME }}" >> $GITHUB_ENV
                  echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
                  echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> $GITHUB_ENV

            - name: Decode Firebase service account key
              run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE64 }}" | base64 --decode > $GITHUB_WORKSPACE/firebase-key.json

            - name: Decode Google service account key
              run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}" | base64 --decode > $GITHUB_WORKSPACE/google-credentials.json

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.x' # Or specify your desired Python version

            - name: Install dependencies
              run: |
                  pip install -r requirements.txt

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '22' # Adjust to your desired Node.js version

            - name: Install NPM dependencies
              run: npm install firebase-tools@13.13.1

            - name: Connect to Surfshark VPN (if required)
              if: ${{ secrets.SURFSHARK_PROXY_USERNAME }} && ${{ secrets.SURFSHARK_PROXY_PASSWORD }}
              run: |
                  sudo apt-get update
                  sudo apt-get install openvpn -y
                  # (Rest of your Surfshark VPN setup commands as before)

            - name: Ensure BASE_DIR exists
              run: mkdir -p ${{ secrets.BASE_DIR }}

            - name: Run Python scripts
              run: |
                  python3 in/in-new.py
                  python3 rw/main.py
              env:
                  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
                  BASE_DIR: ${{ secrets.BASE_DIR }}
                  GOOGLE_APPLICATION_CREDENTIALS: $GITHUB_WORKSPACE/google-credentials.json
                  DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
                  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
                  MONGO_URI: ${{ secrets.MONGO_URI }}

            - name: Deploy to Firebase
              uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: ${{ secrets.GITHUB_TOKEN }}
                  firebaseServiceAccount: $GITHUB_WORKSPACE/firebase-key.json
                  channelId: live
                  projectId: auto-cryptoskopen-1 # Replace with your project ID
                  expires: 7d
                  entryPoint: ${{ secrets.BASE_DIR }}
